language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test:once
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
